// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "personalblog-20190106221204-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://personalblog-20190106221204-hostingbucket.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
